// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg5SU3AFtcJ7M1fwAK4_RbXM7xXn4xnXc',
    appId: '1:476086399204:web:feac8cc352e1f71b287cf1',
    messagingSenderId: '476086399204',
    projectId: 'course-hotelio-5b501',
    authDomain: 'course-hotelio-5b501.firebaseapp.com',
    storageBucket: 'course-hotelio-5b501.appspot.com',
    measurementId: 'G-8G128MMJWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkoyIxskeIyPZovp_b5aoTQSMz2Nm3IWY',
    appId: '1:476086399204:android:a00d2fc8d2184492287cf1',
    messagingSenderId: '476086399204',
    projectId: 'course-hotelio-5b501',
    storageBucket: 'course-hotelio-5b501.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrJPtJOYssmyBP2g08QGlXe8H0JD9TkxQ',
    appId: '1:476086399204:ios:2e0952e9965abc21287cf1',
    messagingSenderId: '476086399204',
    projectId: 'course-hotelio-5b501',
    storageBucket: 'course-hotelio-5b501.appspot.com',
    iosClientId: '476086399204-leeod9ev5hekcjqv4v5l76qic9lpdvpl.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseHotelio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrJPtJOYssmyBP2g08QGlXe8H0JD9TkxQ',
    appId: '1:476086399204:ios:a17c9d1923548c85287cf1',
    messagingSenderId: '476086399204',
    projectId: 'course-hotelio-5b501',
    storageBucket: 'course-hotelio-5b501.appspot.com',
    iosClientId: '476086399204-7bhee7fqhus7gtp8dgu99kfqje68mdnk.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseHotelio.RunnerTests',
  );
}
